@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTagPersonCommandParser" as AddTagPersonCommandParser LOGIC_COLOR
participant "c:AddTagPersonCommand" as AddTagPersonCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:ModelManager" as ModelManager MODEL_COLOR
end box

[-> LogicManager : execute("addTagPerson 1 t/caterer")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addTagPerson 1 t/caterer")
activate AddressBookParser

create AddTagPersonCommandParser
AddressBookParser -> AddTagPersonCommandParser : AddTagPersonCommandParser()
activate AddTagPersonCommandParser

AddTagPersonCommandParser --> AddressBookParser
deactivate AddTagPersonCommandParser

AddressBookParser -> AddTagPersonCommandParser : parse("1 t/caterer")
activate AddTagPersonCommandParser

create AddTagPersonCommand
AddTagPersonCommandParser -> AddTagPersonCommand : AddTagPersonCommand(index, tags)
activate AddTagPersonCommand

AddTagPersonCommand --> AddTagPersonCommandParser : c
deactivate AddTagPersonCommand

AddTagPersonCommandParser --> AddressBookParser : c
deactivate AddTagPersonCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTagPersonCommandParser -[hidden]-> AddressBookParser
destroy AddTagPersonCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> AddTagPersonCommand : execute(m)
activate AddTagPersonCommand

AddTagPersonCommand -> ModelManager : getFilteredPersonList()
activate ModelManager

ModelManager --> AddTagPersonCommand : lastShownPersonList
deactivate ModelManager

'Create edited task
AddTagPersonCommand -> AddTagPersonCommand : createEditedPerson(personToEdit, tagsToAdd)
activate AddTagPersonCommand
AddTagPersonCommand --> AddTagPersonCommand : editedPerson
deactivate AddTagPersonCommand

AddTagPersonCommand -> ModelManager : setPerson(personToEdit, editedPerson)
activate ModelManager

ModelManager --> AddTagPersonCommand
deactivate ModelManager

AddTagPersonCommand -> ModelManager : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate ModelManager

ModelManager --> AddTagPersonCommand
deactivate ModelManager

create CommandResult
AddTagPersonCommand -> CommandResult : CommandResult(MESSAGE_EDIT_PERSON_SUCCESS)
activate CommandResult

CommandResult --> AddTagPersonCommand : r
deactivate CommandResult

AddTagPersonCommand --> LogicManager : r
deactivate AddTagPersonCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTagPersonCommand -[hidden]-> LogicManager
destroy AddTagPersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
