@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteTaskCommandParser" as DeleteTaskCommandParser LOGIC_COLOR
participant "c:DeleteTaskCommand" as DeleteTaskCommand LOGIC_COLOR
end box

[-> LogicManager : execute("deleteTask 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteTask 1")
activate AddressBookParser

create DeleteTaskCommandParser
AddressBookParser -> DeleteTaskCommandParser : DeleteTaskCommandParser()
activate DeleteTaskCommandParser

DeleteTaskCommandParser --> AddressBookParser
deactivate DeleteTaskCommandParser

AddressBookParser -> DeleteTaskCommandParser : parse("1")
activate DeleteTaskCommandParser

create DeleteTaskCommand
DeleteTaskCommandParser -> DeleteTaskCommand : DeleteTaskCommand(index)
activate DeleteTaskCommand

DeleteTaskCommand --> DeleteTaskCommandParser : c
deactivate DeleteTaskCommand

DeleteTaskCommandParser --> AddressBookParser : c
deactivate DeleteTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteTaskCommandParser -[hidden]-> AddressBookParser
destroy DeleteTaskCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> DeleteTaskCommand : execute(m)
activate DeleteTaskCommand

ref over DeleteTaskCommand: Delete task in task list

ref over DeleteTaskCommand: Create successful CommandResult

DeleteTaskCommand --> LogicManager : r
deactivate DeleteTaskCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteTaskCommand -[hidden]-> LogicManager
destroy DeleteTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
