@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkTaskCommandParser" as MarkTaskCommandParser LOGIC_COLOR
participant "idx:ParserUtil" as ParserUtil LOGIC_COLOR
participant "cmd:MarkTaskCommand" as MarkTaskCommand LOGIC_COLOR
end box

[-> LogicManager : execute("markTask 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("markTask 1")
activate AddressBookParser

create MarkTaskCommandParser
AddressBookParser -> MarkTaskCommandParser : MarkTaskCommandParser()
activate MarkTaskCommandParser

MarkTaskCommandParser --> AddressBookParser
deactivate MarkTaskCommandParser

AddressBookParser -> MarkTaskCommandParser : parse("1")
activate MarkTaskCommandParser

create ParserUtil
MarkTaskCommandParser -> ParserUtil : parseIndex("1")
activate ParserUtil

ParserUtil --> MarkTaskCommandParser : idx
deactivate ParserUtil

create MarkTaskCommand
MarkTaskCommandParser -> MarkTaskCommand : MarkTaskCommand(idx)
activate MarkTaskCommand

MarkTaskCommand --> MarkTaskCommandParser : cmd
deactivate MarkTaskCommand

MarkTaskCommandParser --> AddressBookParser : cmd
deactivate MarkTaskCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkTaskCommandParser -[hidden]-> AddressBookParser
destroy MarkTaskCommandParser

AddressBookParser --> LogicManager : cmd
deactivate AddressBookParser

LogicManager -> MarkTaskCommand : execute()
activate MarkTaskCommand

ref over MarkTaskCommand: Mark task in task list

ref over MarkTaskCommand: Create successful CommandResult

MarkTaskCommand --> LogicManager : res
deactivate MarkTaskCommand

[<--LogicManager : res
deactivate LogicManager

destroy ParserUtil
destroy MarkTaskCommand
@enduml
