@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Create successful CommandResult

participant "cmd:FindTaskCommand" as FindTaskCommand LOGIC_COLOR
participant "res:CommandResult" as CommandResult LOGIC_COLOR

create CommandResult
FindTaskCommand -> CommandResult : CommandResult(MESSAGE_TASKS_LISTED_OVERVIEW)
activate CommandResult

CommandResult --> FindTaskCommand : res
deactivate CommandResult

@enduml
