@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Create Task Predicate

participant ":FindTaskCommandParser" as FindTaskCommandParser LOGIC_COLOR
participant "pred:TaskContainsKeywordsPredicate" as TaskContainsKeywordsPredicate LOGIC_COLOR

create FindTaskCommandParser
create TaskContainsKeywordsPredicate
FindTaskCommandParser -> TaskContainsKeywordsPredicate : TaskContainsKeywordsPredicate(["agenda"])
activate TaskContainsKeywordsPredicate

TaskContainsKeywordsPredicate --> FindTaskCommandParser : pred
deactivate TaskContainsKeywordsPredicate

@enduml
