@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

mainframe: **sd** Create successful CommandResult

participant "cmd:EditTaskCommand" as EditTaskCommand LOGIC_COLOR
participant "res:CommandResult" as CommandResult LOGIC_COLOR

create CommandResult
EditTaskCommand -> CommandResult : CommandResult(MESSAGE_EDIT_TASK_SUCCESS)

activate CommandResult
CommandResult --> EditTaskCommand : res
deactivate CommandResult

@enduml
